### ISSUE TITLE
Aggiungere nuova funzione

### ISSUE THREAD

**Issue by Koinokalo** [ABuffEr/rssowlnixSupport#1]
Volevo sapere se qualcuno è in grado di aggiungere delle nuove funzionalità al programma. In particolare la possibilità di esportare in un file CSV tutti i dati dei feed mediante selezione singola.
Aggiungere al MENU "Condividi" la voce export CSV e consentire di selezionare i campi da esportare (Gli stessi presenti nelle preferenze).
Aggiungere il link alla immagine.

Per chi fosse interessato anche con contributo può contattarmi a
giovanni.erra@koinokalo.it

Grazie

**Comment by ABuffEr** [comment]
Ciao @Koinokalo ,
questo non è il repository del programma, di cui non sono l'autore. Devi sentire [qui.](https://github.com/Xyrio/RSSOwlnix/issues)
