### ISSUE TITLE
Does RSSOwlnix have a Windows installer?

### ISSUE THREAD

**Issue by amirsol81** [ABuffEr/rssowlnixSupport#2]
Greetings. Would you please help me install RSSOwlnix on Windows? And any chance of updating the NVDA add-on to support the latest NVDA alphas beyond 23988? I'm using Windows 11 and with the demise of Internet Explorer and its simple but convenient RSS reader, am really stuck without an efficient RSS reading solution. Maybe RSSOwlnix is it.
Thanks.

**Comment by ABuffEr** [comment]
Hi @amirsol81 ,
about the add-on, I'll surely update it; for the moment I'm using alpha 23986, but when situation comes a bit more stable I'll jump to current alpha and update all accordingly.
About RSSOwlnix, I must alert you: it's not the most simple program out there, requires some configuration, view optimizations... but in my experience it's very accessible (and maybe the only at this advanced level).
However, no, it has no installers, only standalone .zip versions, that you find under [release page](https://github.com/Xyrio/RSSOwlnix/releases), expanding the first "Assets" button.

**Comment by amirsol81** [comment]
Thanks, Alberto, for the useful tips! I'll definitely give the app a try and will even downgrade to NVDA 23986 to take advantage of your add-on. BTW also looking forward to the update of your awesome Columns Review add-on -- it's yet another awesome life-saver!

**Comment by amirsol81** [comment]
And would you please give me a link for a Java Runtime Environment (JRE) or Java Development Kit (JDK)? The app doesn't run without it and I don't know where to get such a thing.
Thanks.

**Comment by ABuffEr** [comment]
Hi @amirsol81 ,
well, JRE/JDK situation has became quite complicated, I have them for other reasons, but for your case I suggest you to:

* download [this portable version](https://portableapps.com/apps/utilities/java_portable), 32 or 64-bit according to your RSSOwlnix/Windows;
* run initial procedure to get all files;
* find the folder containing bin, lib etc (probably called Java);
* rename it to JRE;
* put this folder in rssowlnix.exe path.

Anyway, do not use issues for discussion like this, write me a mail, without problems (you can find address in my add-ons info): mail is sent more quickly than Github notifications, and I remember more easily to answer when I have time 🙂

**Comment by amirsol81** [comment]
Mega thanks, @ABuffEr for the points! It's now working as expected. Just looking forward to your updated add-on.
